### ISSUE TITLE
numerous number of files reside on session folder

### ISSUE THREAD

**Issue by agtabesh** [adonisjs/adonis-session#13]
Hi there,

I'm using AdonisJs version 4.1 but I faced with a problem on storing session.
I've atmost **650k** unique visitor per month but the size of `sessions` directory has grown up to **16GB** which is a little bit weird. 

Is there someone who has had such problem?
Why does the size of `sessions` directory has grow in such way?

Any help will be appreciated.
Best regards.

**Comment by thetutlage** [comment]
One file is created for each session and since there is no way to set expiry on files, the number will keep growing.

A quick way is to have a cleanup task, which deletes the files older than a given timeframe. If a user session is active, AdonisJs will update the file timestamp.

The best option is to change the driver from `file` to `redis` or `cookies`. The `redis` driver sets the `ttl` on session values and Redis will clear the older values by itself and with `cookie` driver, the store is in the cookies and not your server

**Comment by agtabesh** [comment]
Many of session file has almost **61 bytes** and by a simple math, `61 * 650k`, what results in is almost **40MB** of storage to store all of those session files which is far different from **16GB** I already have.

If I use `redis` as session storage, does these many expiration time add an extra overhead on `redis` itself and reduce its performance?

Thank you.
Best regards.

**Comment by thetutlage** [comment]
Nope, Redis as inbuilt support for expiry and doesn't impact any sort of performance.

Regarding the files size, you shouldn't rely on your analytics numbers and map them as one to one with sessions. Simply check the number of files you have in the folder. Also, as I said earlier, a simply script to cleanup old files can cleanup most of the disk

**Comment by agtabesh** [comment]
Thank you so much. I'm gonna switch session driver to `redis`.
